import streamlit as st
import re

from app.components.footer import render_footer
from app.components.navbar import render_navbar
from app.components.sidebar import render_sidebar
from app.runtime import (
    get_export_service,
    get_query_service,
    initialize_state,
    load_styles,
)

st.set_page_config(
    page_title="Engineering Reports | AI_FOIS",
    page_icon="✈️",
    layout="wide",
)

initialize_state()
load_styles()
render_sidebar()
render_navbar()

st.markdown(
    """
    <div class="hero">
        <div class="eyebrow">Decision archive / traceable outputs</div>
        <h1>Engineering Reports</h1>
        <p>
            Review engineering conclusions, recommendations,
            exported reports, and operational risk assessments.
        </p>
    </div>
    """,
    unsafe_allow_html=True,
)

reports = get_query_service().report_service.recent()
export_service = get_export_service()

if not reports:
    st.info("No engineering reports have been generated yet.")
    render_footer()
    st.stop()

search = st.text_input(
    "Search reports",
    placeholder="Search by summary, recommendation or risk..."
)

st.caption(f"{len(reports)} reports available")

for report in reports:

    searchable = " ".join(
        [
            str(report.get("summary", "")),
            str(report.get("recommendation", "")),
            str(report.get("risk", "")),
        ]
    ).lower()

    if search and search.lower() not in searchable:
        continue

    title = report.get("title") or "Engineering Report"
    summary = str(report.get("summary") or "No summary available.")

    preview = (
        summary[:350] + "..."
        if len(summary) > 350
        else summary
    )

    risk = report.get("risk") or "Not specified"
    system = report.get("system") or "Not specified"

    st.markdown("---")

    left, right = st.columns([5, 1])

    with left:

        st.markdown(
            f"""
### {title}

**Created:** {report["created_at"]}

**System:** {system}

**Risk:** `{risk}`
"""
        )

        st.write(preview)

    with right:

        st.metric(
            "Summary",
            f"{len(summary.split())} words"
        )

    with st.expander("View Full Report"):

        # Clean ugly Markdown generated by the LLM
        clean_summary = summary

        # Remove separator lines (==========)
        clean_summary = re.sub(r"=+", "", clean_summary)

        # Remove AI generated report title
        clean_summary = re.sub(
            r"#\s*AI_FOIS.*?REPORT",
            "",
            clean_summary,
            flags=re.IGNORECASE,
        )

        # Reduce heading sizes
        clean_summary = re.sub(r"^# ", "### ", clean_summary, flags=re.MULTILINE)
        clean_summary = re.sub(r"^## ", "#### ", clean_summary, flags=re.MULTILINE)

        st.markdown(f"## {title}")
        st.markdown(clean_summary)

        if report.get("recommendation"):

            st.markdown("### Recommendation")
            st.write(report["recommendation"])

        if report.get("risk"):

            st.markdown("### Risk Assessment")
            st.write(report["risk"])

        if report.get("references"):
            st.markdown("### References")
            st.write(report["references"])

        st.divider()

        c1, c2, c3 = st.columns(3)

        with c1:

            st.download_button(
                "⬇ Markdown",
                data=export_service.export(report, "markdown"),
                file_name=f"engineering_report_{report['report_id']}.md",
                mime="text/markdown",
                key=f"md_{report['report_id']}",
                use_container_width=True,
            )

        with c2:

            st.download_button(
                "⬇ JSON",
                data=export_service.export(report, "json"),
                file_name=f"engineering_report_{report['report_id']}.json",
                mime="application/json",
                key=f"json_{report['report_id']}",
                use_container_width=True,
            )

        with c3:

            st.download_button(
                "⬇ PDF",
                data=export_service.export(report, "pdf"),
                file_name=f"engineering_report_{report['report_id']}.pdf",
                mime="application/pdf",
                key=f"pdf_{report['report_id']}",
                use_container_width=True,
            )

render_footer()