from datetime import datetime
from src.exceptions import ExportError


class MarkdownExporter:
    """Exports engineering reports as Markdown."""

    def export(self, report: dict) -> str:
        try:
            created = report.get(
                "created_at",
                datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            )

            markdown = f"""# {report.get("title", "Engineering Report")}

**Generated:** {created}

**System:** {report.get("system", "Not specified")}

---

## Summary

{report.get("summary", "N/A")}

---

## Recommendation

{report.get("recommendation", "N/A")}

---

## Risk Assessment

{report.get("risk", "N/A")}

---

## References

{report.get("references", []) or "No references available."}

---

Generated by **FOIS**
Flight Operations Intelligence System
"""

            return markdown
        except Exception as error:
            raise ExportError("Unable to export engineering report.") from error